nationalarchives/tdr-e2e-tests

Jenkinsfile, application.conf, application.intg.conf, application.staging.conf, build.sbt, src/test/resources/features/Login.feature, src/test/scala/helpers/steps/StepsUtility.scala, src/test/scala/runners/TestRunner.scala, src/test/scala/steps/LoginSteps.scala
Add basic gherkin feature to test a user logging in
Using a chromedriver for testing
Driver location, user name and password passed in as environment variables
Jenkins job requires user name and password as params to the build
=> Initial test setup

Jenkinsfile
AWS container upgraded to python 3
Updating Jenkins script to reference python 3
=> Upgraded Jenkins build to python3

src/test/resources/features/Fullflow.feature, src/test/resources/features/Series.feature, src/test/resources/features/TransferAgreement.feature, src/test/scala/steps/Steps.scala
This adds a test with the full 'happy path' user flow how TDR currently works. It is a bit lengthy but might be helpful if we want a single test to say that TDR is working when all conditions are right.
=> Add full user flow test

src/test/resources/features/Fullflow.feature, src/test/resources/features/Login.feature, src/test/resources/features/Series.feature, src/test/resources/features/TransferAgreement.feature, src/test/resources/features/Upload.feature, src/test/scala/helpers/steps/StepsUtility.scala, src/test/scala/runners/TestRunner.scala, src/test/scala/steps/Steps.scala
Due to the bug(s), most of the uploads test are not working when headless; they do work headless so they have been marked as wip
=> Multiple file uploads

src/test/resources/features/Series.feature, src/test/scala/steps/Steps.scala
Error handling updated to display a general service error message
=> Update error message and HTML

src/test/resources/features/Dashboard.feature, src/test/resources/features/FileChecks.feature, src/test/resources/features/Login.feature, src/test/resources/features/Series.feature, src/test/resources/features/TransferAgreement.feature, src/test/resources/features/Upload.feature, src/test/scala/steps/Steps.scala
Additional tests for current flow where a logged out user tries to access a page which requires a logged in user
=> Tests for 403 and 404 errors

logback.xml, src/test/resources/logback.xml, src/test/scala/helpers/aws/AWSUtility.scala, src/test/scala/steps/Steps.scala
- Create a variable for AWSUtility
- Add explicit credential provider to sts call
- Make the provider lazy
- Logback config to stop the apache http spam
=> Assume role changes and logback config

src/test/resources/features/TransferAgreement.feature
Senario step wording not updated inline with step definition
=> Update scenario step wording

src/test/resources/features/TransferConfirmation.feature, src/test/resources/features/TransferSummary.feature
- Update the test with the new page name
- Add a test for the transfer confirmation page.
=> Transfer confirmation updates

src/test/scala/steps/Steps.scala
Requires PR: https://github.com/nationalarchives/tdr-transfer-frontend/pull/459
=> Change to checkboxes on transfer agreement form

src/test/resources/features/TransferSummary.feature
Temporarily disable scenario whilst investigate how to get correct checksums from test files into database
=> Disable failing scenario

src/test/resources/features/TransferSummary.feature
Transfer summary is now Confirm transfer
=> Fixed the heading

src/test/scala/steps/Steps.scala
Now we show an error page if the checksums don't match, we need to make sure they do match if we're expecting the success page. This adds them in.
=> Use real checksums for backend checksum data.

src/test/resources/features/FileChecks.feature, src/test/scala/helpers/graphql/GraphqlUtility.scala, src/test/scala/steps/Steps.scala
Depends on PR: https://github.com/nationalarchives/tdr-consignment-api/pull/138
=> Tdr 1064 password protected file status

src/test/resources/features/FileChecks.feature, src/test/scala/steps/Steps.scala
Depends on PR: https://github.com/nationalarchives/tdr-consignment-api/pull/139
=> Tdr 1068 zip file status

src/test/resources/features/FileChecks.feature, src/test/resources/features/Fullflow.feature, src/test/resources/features/RecordsResults.feature, src/test/scala/helpers/steps/StepsUtility.scala, src/test/scala/steps/Steps.scala
- Change the tests to work with the new file checks page.
- Extract waitForElementTitle
=> Change tests for new file checks

src/test/resources/features/FileChecks.feature, src/test/resources/features/Fullflow.feature, src/test/resources/features/RecordsResults.feature, src/test/resources/features/Upload.feature, src/test/scala/steps/Steps.scala
Also update to show we're using the new success summary component.
=> Update the title for the records check page

Jenkinsfile
Jenkins transfer-frontend image node has upgraded Firefox version
=> Upgrade gecko version due to Firefox upgrade

src/test/resources/features/SignOut.feature
The step says TDR Start Page not start Page. I've updated it.
=> Use upper case S

.github/workflows/ci.yml
This should be fine and is needed now we're running the tests on pull
requests.
=> Allow jobs to run in parallel.

src/test/resources/features/Fullflow.feature, src/test/resources/features/Series.feature, src/test/scala/steps/Steps.scala
e2e test fixes due to series page now having a consignment created
=> Tdr-1812 Series completed e2e

src/test/resources/features/BeforeUploading.feature, src/test/resources/features/Homepage.feature
=> Temp disable tests that contain 'court judgment' to account for change

src/test/resources/features/JudgmentFullflow.feature
Requires PR: https://github.com/nationalarchives/tdr-transfer-frontend/pull/1843
Judgment results of checks page design updated to improve user experience
=> Update button name

src/test/scala/helpers/users/RandomUtility.scala
E2E test are failing because the created password for the user credentials don't currently meet the newly added password policy.
- Minimum 8 characters
- Must include 1 Uppercase
- Must include 1 Digit
I'm not too sure how secretive the passwords have to be, so I've just made it so it keeps randomly generating a alphanumeric string until it meets the above requirements. Instead of hard coding a valid String.
=> Tdr-2316 e2e tests to meet new password policy

project/Dependencies.scala, src/test/scala/helpers/graphql/GraphqlUtility.scala, src/test/scala/steps/Steps.scala
They've been updated in the API and these need to match.
=> Update Graphql type names.

src/test/scala/steps/Steps.scala
Fix the failing tests in due to datetime changes in the download CSV
=> Fix broken test due to datetime changes in download csv

README.md, src/test/resources/features/ConfirmTransfer.feature, src/test/resources/features/StandardFullflow.feature, src/test/resources/features/TransferAgreementCompliance.feature, src/test/scala/steps/Steps.scala
Fix for the e2e tests once the openrecords checkbox is removed from the ConfirmTransfer page
=> TDR-2494 Remove check for openrecords checkbox

src/test/resources/features/FileChecksResults.feature, src/test/resources/features/StandardFullflow.feature
Requires PR: https://github.com/nationalarchives/tdr-terraform-environments/pull/295
=> Account for 'additional metadata' steps

src/test/scala/helpers/steps/StepsUtility.scala, src/test/scala/steps/Steps.scala
This commit has the added benefit of potentially solving the constant TA compliance page failures that we've been getting.
=> Add more detailed error messages to TimeoutExceptions

src/test/resources/features/ClosureMetadata.feature, src/test/resources/features/DescriptiveMetadata.feature, src/test/scala/steps/Steps.scala
also fixed metadata tests failing due to the title changes
=> Fix e2e test for new view transfer ui

project/Dependencies.scala, src/test/scala/helpers/graphql/GraphqlUtility.scala
=> TDR-2824 - Droid extention mismatch

.github/workflows/upsert-scala-steward-dependencies-branch.yml
It seems the email and username is required in this repo for the upsert script.
https://github.com/nationalarchives/tdr-e2e-tests/actions/runs/8062868528/job/22023527811
=> Add email and name to upsert script

README.md, src/test/scala/steps/Steps.scala
Test was failing due to removing time from the metadata csv
=> Fix download metadata test

src/test/resources/features/FileChecksResults.feature, src/test/resources/features/StandardFullflow.feature, src/test/scala/steps/Steps.scala
Changes related to: https://github.com/nationalarchives/tdr-transfer-frontend/pull/3803
Staging e2e tests will be broken until we apply terraform-environments for staging env.
=> Add metadata `entry-method` page to e2e tests

.github/scripts/update-security-group.sh, .github/workflows/ci.yml
- Add the IP in the security group only if it doesn't exist
- Delete only if the IP exists in the security group
=> Tdrd 102 fix ip authorizaion issue

README.md, project/Dependencies.scala, src/test/resources/features/DownloadMetadata.feature, src/test/scala/helpers/drivers/DriverUtility.scala, src/test/scala/helpers/steps/StepsUtility.scala, src/test/scala/steps/Steps.scala
Update to Scala Test Play and removal of CSV download test (in prep for replacing with Excel download test)
=> Tdrd 58 upgrade scala test play

src/test/resources/testfiles/draft-metadata.csv
draft-metadata.csv requires description
=> Fix draft-metadata test

src/test/resources/features/BeforeUploading.feature, src/test/resources/features/FileChecks.feature, src/test/resources/features/Homepage.feature, src/test/resources/features/JudgmentFullflow.feature, src/test/resources/features/Upload.feature
update tests for changes that https://github.com/nationalarchives/tdr-transfer-frontend/pull/4079 will bring in
=> TDRD-352, TDRD-356 and TDRD-311: update features for front end html changes

src/test/resources/testfiles/draft-metadata.csv, src/test/resources/testfiles/invalid-draft-metadata.csv, src/test/scala/steps/Steps.scala
The draft-metadata files need to have BOM at beginning to pass UTF-8 validation
=> Utf 8 bom invalid draft metadata.csv
