nationalarchives/tdr-e2e-tests

- application.conf
- build.sbt
Keycloak auth server has been updated to use v9.0.0. Client Keycloak version must match server version
Removed unnecessary dependencies following upgrade to newer version of Keycloak
Changed local auth port to match local auth server setup instructions
> Upgraded keycloak version to v9.0.0

- src/test/resources/features/Login.feature
- src/test/resources/features/Series.feature
- src/test/scala/helpers/users/KeycloakClient.scala
- src/test/scala/steps/Steps.scala
These e2e test alterations mean that they now work after the major changes TDR has gone through in the past few weeks. These changes will apply to a dedicated Jenkins build, though more changes may need to be made so that the tests work on Jenkins.
After looking at Jenkins build options for the e2e tests, I think my changes need to be merged into master before I can start to try getting them working on Jenkins.
> Get existing e2e test up to date with TDR

- src/test/resources/features/Login.feature
- src/test/scala/helpers/users/KeycloakClient.scala
- src/test/scala/steps/Steps.scala
One of the tests had the wrong wording meaning it defaulted to a different step and was ambiguous. This is now changed, and a step that is not used has been removed.
> Fix test wording and refactor.

- Jenkinsfile
Upgrade to Chrome 83 for compatibility with the Chrome version on the latest nationalarchives/jenkins-build-transfer-frontend Docker image.
This should fix the failing end-to-end tests.
> Upgrade Chrome webdriver

- Jenkinsfile
Let developers know when failing end-to-end tests have been fixed. This shouldn't add too much noise because it won't notify Slack on _every_ successful build, just when the build goes from red to green.
> Notify Slack when the tests start passing again

- application.conf
- application.intg.conf
- application.staging.conf
- src/test/resources/features/Series.feature
- src/test/resources/features/TransferAgreement.feature
- src/test/scala/steps/Steps.scala
This change adds e2e test steps for the transfer agreement page. At the moment these changes are could use some refactoring. The transfer agreement form only works when consignment ID is in the URL, but to get to that stage the test 'user' needs to go through the series selection to get directed to the correct transfer agreement page. At the moment this is done by adding quite a few steps to the scenario, but I think it could be smoother.
Also removed some redundant code in the application conf files.
> Add e2e tests for Transfer Agreement Page

- src/test/resources/features/Login.feature
- src/test/resources/features/Series.feature
- src/test/scala/steps/Steps.scala
This also allows for more 'human' readable language used in scenarios and steps. I have removed steps that reference specific element CSS class names etc in favour of text that shows on the user side so that tests are a bit easier to read. Also means we can compare these to acceptance criteria more easily.
> Slight refactoring of tests and steps to remove repetitive code

- src/test/resources/features/Series.feature
- src/test/resources/features/TransferAgreement.feature
- src/test/scala/steps/Steps.scala
This change adds test scenarios to make sure that the Transfer Agreement form can only be submitted when completed correctly. This will need updated when we add extra options for the form in future. Fixes TDR-288
> Test to ensure user can't submit incomplete TA form

- Jenkinsfile
The success message has now been changed to make it more clear that it has succeeded after a previous failure. I have also changed the wording of the failure message to match the phrasing of the success message.
> Change wording of slack message to be more clear

- README.md
- src/test/resources/features/Fullflow.feature
- src/test/resources/features/Upload.feature
No longer skip any tests that include upload steps
Upload steps will run correctly on Firefox in headless mode
Silent SSO login now implemented to make upload steps more robust as no longer a page refresh on the upload page: https://national-archives.atlassian.net/jira/software/projects/TDRB/boards/6?selectedIssue=TDR-327
> Reinstate upload Features

- src/test/resources/features/Fullflow.feature
- src/test/resources/features/Upload.feature
- src/test/scala/steps/Steps.scala
"Progress bar visible" test intermittently failing. Caused by the file upload completing, and page redirect occuring before test completed check for progress bar element. The element was not present on the redirect page, causing the condition to timeout, and the test to fail
Increased the upload file size for the "Progress bar visible" to 10mb. With this size file the test passed 10 times in row during testing
> Increase upload file size

- src/test/resources/features/Fullflow.feature
- src/test/resources/features/Upload.feature
This change removes steps describing test user on 'records' page and replaces it with the correct 'Checking your records' page.
> Fix file check page name in e2e tests as name changed in TDR FE

- README.md
> Fix link to Geckodriver releases in Readme

- build.sbt
The e2e tests actually still work on the old libraries but we may as
well keep them up to date.
> Update keycloak libraries to 11.0.1

- src/test/resources/features/Fullflow.feature
Tests needed to have quotation marks ("") around page titles to follow step definition. This was causing Jenkins runs to be unstable.
> Change step usage to fix unstable tests on Jenkins

- src/test/resources/features/FileChecks.feature
- src/test/resources/features/Fullflow.feature
- src/test/scala/helpers/graphql/GraphqlUtility.scala
- src/test/scala/steps/Steps.scala
These changes add a test scenario for the FFDIMetadata progress bar, with a new GraphqlUtility function to add FFIDMetadata to the appropriate table and, removes the manual upload scenario from the fileChecks scenarios file.
I have added a step to simulate the user waiting for backend checks to complete, to allow us to check that the redirect only happens when all checks are complete and to let us remove the 'manual' test user upload. This functionality is a little clumsy at the moment and definitely needs refactoring, but I was unsure of which direction to go with it.
> Tdr 414 ffid progress

- Jenkinsfile
I've moved the jenkins front end build image to alpine and the alpine
version of wget doesn't support the -N argument. I've tried running the
job without it and it works fine.
> Remove invalid wget argument

- src/test/resources/features/FileChecks.feature
- src/test/resources/features/Fullflow.feature
These tests will continue to fail until a solution is found for the test user uploading process, so will not be run until this is fixed.
> Add '@wip' to stop broken tests from being run while fixing

- src/test/scala/helpers/keycloak/KeycloakClient.scala
Trying to delete non-existent user was causing errors
This was because trying to retrieve the non-existent user before using the remove method
Changed to using delete method
> Change user deletion method

- src/test/resources/features/FileChecks.feature
- src/test/resources/features/FileChecksResults.feature
- src/test/resources/features/Fullflow.feature
- src/test/resources/features/RecordsResults.feature
- src/test/scala/helpers/graphql/GraphqlUtility.scala
- src/test/scala/steps/Steps.scala
This work adds an E2E test feature file for the fileChecksResults page and fixes existing tests to reflect the addition of this page. 
One of the step functions has been altered to feed in a parent folder name thus allowing us to check the fileChecksResults page since it no longer returns an error.
> Record checks results tests

- src/test/resources/logback.xml
- src/test/scala/helpers/aws/AWSUtility.scala
- src/test/scala/helpers/keycloak/KeycloakClient.scala
- src/test/scala/steps/Steps.scala
It looks like this was failing because the apache http client was running out of threads in the pool. I think this is because we're creating a new keycloak client for every user which is wasteful anyway so I've changed these to lazy vals, so they'll only be created on first use.
We probably will encounter some problems later with these values being cached but for now, this is working.
> Change log level and make keycloak client lazy

- src/test/resources/features/Series.feature
- src/test/scala/steps/Steps.scala
The front end has been updated to add an error summary element and to
change the wording of the error summary.
This test has been updated to check for the correct new text and check
for the new element.
> Update series error test with new text and error

- src/test/scala/helpers/steps/StepsUtility.scala
- src/test/scala/steps/Steps.scala
The upload form is no longer hiding things with css but using the hidden attribute instead so the e2e tests need to be updated to check for this instead.
> Change the way we check if progress bar is hidden

- src/test/scala/helpers/graphql/GraphqlUtility.scala
* The test that was waiting for the export to complete was failing.
* The export was failing because I recently deployed the change to fail if there are no files returned for the consignment.
* The API only returns files which have passed the antivirus.
* The method in the e2e tests which creates the dummy results for the AV checks populates the Result field.
* If the Result field is anything other than empty string, it counts as an AV failure and the API won't return the files and so the export won't pass.
> Set an empty result so the AV shows as passed

- src/test/resources/features/TransferAgreement.feature
We are adding the error summary to the transfer agreement page, this test checks that it's there.
> Add test for the error summary.

- src/test/resources/features/Series.feature
- src/test/scala/steps/Steps.scala
This link was removed from the frontend: https://github.com/nationalarchives/tdr-transfer-frontend/pull/444
> Remove test for Back link on series page

- Jenkinsfile
We were using fixed in the post block but this would fire if the previous test run was for staging which failed and then the next test run for integration started working which isn't what we want.
This now moves recursively through the previous builds until it finds the previous one with the same stage as the current build and then returns that status.
> Change the way we check if the previous build failed.

- src/test/scala/helpers/logging/AssertionErrorMessages.scala
- src/test/scala/steps/Steps.scala
Error message to help when trying diagnose why a test has failed
In some case a simple assertion error in the logs does not make it clear what exactly has failed
> Provide error messages for assertion failures

- src/test/resources/features/TransferSummary.feature
- src/test/scala/steps/Steps.scala
These changes add a scenario and associated steps function to the E2E tests to ensure all expected information is shown within the transfer summary table. I first attempted to check the values of each transfer summary row, but these can vary (specifically the consignment reference) so specific values cannot be expected.
This is why this is a relatively simple addition to the E2E tests, but we can still update if we add more information to the transfer summary list (by increasing the number of rows we expect within the table).
> Add transfer summary test consignment reference

- src/test/resources/features/TransferSummary.feature
I used an uppercase "S" rather than lowercase for the "Transfer summary" page title, this change fixes that.
> Fix test step word casing to match real TDR title

- src/test/resources/features/TransferSummary.feature
- src/test/scala/steps/Steps.scala
1. Heading level from xl to l
2. 'Transfer complete' has lower case c
> Fixed failed tests

- src/test/resources/features/Upload.feature
- src/test/scala/steps/Steps.scala
Originally, you could try to upload two sets of files. Now, there's a
change so that if one upload is in progress, you're redirected to an
error page. This change reflects that.
> Added a check for the upload in progress page

- src/test/resources/features/FileChecks.feature
- src/test/resources/features/RecordsResults.feature
- src/test/scala/steps/Steps.scala
There's a test to make sure the records page redirects to the error page when there is a checksum error and a check to make sure the record check success message page redirects to the error message if there's an error.
> Add tests for the records errors

- src/test/scala/steps/Steps.scala
This step was failing on staging. We think it might be because Cucumber is checking the button state as soon as the banner appears, but it might be running so fast that it catches the page in the intermediate state when the button hasn't been enabled yet.
This change will force it to wait 2 seconds before failing.
> Add timeout for checking that file check link has been enabled

- src/test/scala/steps/Steps.scala
Add a `WebDriverWait` in the test which checks whether a user can see another user's consignment. This test was failing intermittently because it wasn't waiting for the page to load after logging in.
> Wait for error message to appear after logging in

- src/test/scala/steps/Steps.scala
The 2 second timeout was too short on some people's dev environments, so increase it to 10 seconds. The wait should still be short if the test passes, so this shouldn't slow down most end-to-end test runs.
> Increase timeout in test of authorisation error

- src/test/scala/steps/Steps.scala
The file check API call now runs every 20 seconds rather than every 2 seconds, so we need to wait for longer to make sure the Continue button appears: https://github.com/nationalarchives/tdr-transfer-frontend/pull/833
> Increase wait for file check results button

- src/test/resources/features/FileChecks.feature
- src/test/scala/steps/Steps.scala
This only checks for the correct title text. The rest of the page and
the javascript is the same as the standard user page so there's no need
to duplicate the tests.
> Add a test for the judgment file check results.

- src/test/scala/steps/Steps.scala
Ensure 'userType' is reset otherwise incorrect 'path' is generated for tests causing failures
> Reset 'userType' after each scenario

- src/test/scala/steps/Steps.scala
We used to check if the AWS config object was populated but that has
been removed in the newer version of the sdk so there is now no way to
determin if the cookies endpoint has responded without changing the
frontend just to make the tests work.
So we're just sleeping for 15 seconds. We can always tweak this later.
> Add wait before upload.

- Jenkinsfile
account.number is used by the new GitHub actions tests but isn't being set in the Jenkinsfile.
I've added it in here.
> Set account number in Jenkinsfile

- .github/workflows/ci.yml
This is now failing on every run of the tests. I'm not sure why so I'll
remove it for now.
If this massively slows down the tests, we can try to put it back.
> Remove the cache action.

- .github/workflows/ci.yml
We're hitting the limit on the number of rules a security group can have
because these tests are running at the same time on the same
environment.
This should only allow one set of tests to run per environment now. If
this starts taking for ever with the pull request tests then we can
rethink it but this is the only thing I can think of to stop them
failing all the time now.
> Put the concurrency back in.

- src/test/scala/steps/Steps.scala
This should apply to the:
1. Continue buttons
2. Sign in buttons
3. Start transfer buttons
> Add WebDriverWait to wait for certain buttons to appear on page first

- src/test/scala/steps/Steps.scala
For the standard flow, the 2nd from last element in the url of the homepage is the TDR domain. If the Series page hasn't
loaded at the point of the 'the user should be on a page with series and a consignmentId in the URL' step is called,
the 2nd from last element in the url will be the domain (not the consignmentId) since it's still on the homepage
> Add check for nationalarchives domain in url

- .github/scripts/get_keycloak_secrets.py
- .github/scripts/set_secret_names.py
- .github/workflows/ci.yml
Get secrets from ssm.
The secrets are coming from the repository secrets which are set by terraform. This is then failing every time the secrets are rotated. This should get them from systems manager and pass them to the sbt command.
This https://github.com/nationalarchives/tdr-terraform-environments/pull/261 will need to be deployed to integration and staging before this will work properly.
> Get secrets from SSM

- project/Dependencies.scala
- src/test/resources/features/DownloadMetadata.feature
- src/test/scala/helpers/drivers/DriverUtility.scala
- src/test/scala/helpers/graphql/GraphqlUtility.scala
- src/test/scala/steps/Steps.scala
There are the usual tests checking for page elements and checking access for different user types.
There is also a test that downloads the CSV and checks it for the expected content.
This needs https://github.com/nationalarchives/tdr-generated-graphql/pull/672 before it can be merged.
> Add tests for downloading metadata.

- src/test/scala/steps/Steps.scala
The urls in the front end have been tidied up so none of them now end in
a slash. This needs to be updated to match.
> Remove trailing slash from url

- src/test/resources/features/TransferAgreementPrivateBeta.feature
- src/test/scala/steps/Steps.scala
These checkboxes are not part of integration and staging any more. I've
removed them from the full list of transfer agreement fields and updated
the tests that checks to see what happens if you don't click it.
> Remove allEnglish and openRecords.

- src/test/resources/features/FileChecksResults.feature
- src/test/resources/features/StandardFullflow.feature
- src/test/scala/steps/Steps.scala
This should fix the e2e tests once the content changes for the [file checks results success content changes](https://github.com/nationalarchives/tdr-transfer-frontend/pull/2673) is merged.
> FileChecksResults fix

- src/test/resources/features/StandardFullflow.feature
- src/test/scala/steps/Steps.scala
The Continue button is now Next, the svg icon no longer has a class and
there are two .govuk-button links so we need to select the right one.
The tests won't pass until https://github.com/nationalarchives/tdr-transfer-frontend/pull/2681 but this is ready for review now.
> Updates for the download metadata pages

- src/test/resources/features/DescriptiveMetadata.feature
- src/test/scala/helpers/graphql/GraphqlUtility.scala
- src/test/scala/steps/Steps.scala
The front end has been updated. I've changed the tests to match.
I've also fixed the file checks results checks by setting the consignment status for Upload and adding the parent folder.
There was also an error with the descriptive metadata because the translated title and former reference fields are mandatory. I know they're not supposed to be but it won't hurt to fill them in on the tests. At the moment, the ids are empty and the names end in a dash so this will need to be fixed properly later.
> Update tests to check download columns based on DisplayProperties.

- src/test/resources/features/ClosureMetadata.feature
- src/test/resources/features/DescriptiveMetadata.feature
Confirm closure status before adding closure metadata as it doesn't allow to add closure metadata if closure status is open
> Confirm closure status before adding closure metadata

- src/test/resources/features/ConfirmTransfer.feature
- src/test/scala/steps/Steps.scala
Only the last scenario actually requires the files to be exported thus I've mainly left it as is. The others just check the contents of the confirm transfer page so I've changed it from `an existing upload of # files` to `the file checks are complete` so we don't have to actually upload to S3 for those scenarios.
> Fix confirm transfer e2e tests

- .github/workflows/ci.yml
Small change to the run-name property in ci.yml so that it outputs default value on a pull request but a custom value when run from a different trigger.
> Adding conditional to run name

- src/test/resources/features/FileChecks.feature
We've been seeing a lot of export failures in `intg` recently. This behaviour seems to have been introduced by [this](https://github.com/nationalarchives/tdr-e2e-tests/commit/5cafd615057796b8c8bb4ecd6c4fab0d461e7d2d) commit, where an interim page load test (Results of Checks) is removed. This gives less time for the asynchronous consignment export, kicked off after file checks pass, to complete before the scenario finishes. 
When the scenario finishes, it deletes the test user, on which the consignment export is dependent, causing the failures we have seen. Adding the export complete step to this scenario (which waits until the export package is present in s3) should get rid of this noise.
> Add export complete step to transfer complete page test

- src/test/resources/features/DraftMetadata.feature
Have commented out a couple of tests in DraftMetadata.feature because they will need to be updated to account for the new Excel download and don't want to forget about them. This is a short term fix to make sure the tests are passing until they get updated appropriately.
> Temporarily disabling CSV download checks

- .github/scripts/update-waf-ipset.sh
- .github/workflows/ci.yml
- README.md
- src/test/resources/features/MetadataReview.feature
- src/test/scala/helpers/steps/StepsUtility.scala
- src/test/scala/steps/Steps.scala
- Added new update-waf-script to add github runner ips to the IPSetlist in order to test pages under `/admin` path
- Updated `ci.yml` to call update-waf-script to add/remove IPs
Requires PR: 
- https://github.com/nationalarchives/tdr-terraform-environments/pull/509 
- https://github.com/nationalarchives/tdr-keycloak-user-management/pull/405
A few issues I noticed:
* Feature tests will fail more than usual as they can sometimes fail due to optimistic locking (I tried to mitigate this by having retries & sleeps in the script)
* When new E2E tests run concurrently it causes issues with retaining the original IPSet which we need when we remove the added IPs because others are updating it as others are reading.
We can either
- Merge this pr and deal with the issues if we really want to test …
> TDRD-399 Add Metadata Review e2e test

- src/test/scala/steps/Steps.scala
- think this is what was originally intended, just not updated that bit of a cut and paste?? when it's in just userId it'd replace the "normal user" we make and put in that var, and then that normal user wouldn't get cleaned up
> TDRD-521: use differentUserId for transfer advisor / metadata viewer

- src/test/scala/steps/Steps.scala
As a Before for each scenario we put the feature and scenario in the UserCredentials as last and first name so that we can easily see source of any uncleaned-up test users in the KeyCloak console.
This needs  a`var` to allow update of the credentials for each scenario in a feature.  To ensure that these have been set before we we make "clients" that val needs to be lazy (e.g.):
`lazy val client = GraphqlUtility(userCredentials)`
> TDRD-521: incl feature/scenario in user last/first name
